name: keepalive

on:
  schedule:
    - cron: "*/30 * * * *"   # roda a cada 30 minutos
  workflow_dispatch:         # permite rodar manualmente se quiser

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Curl app
        run: |
          curl -sS --max-time 20 "https://SEU-APP.streamlit.app/" || true
